### ISSUE TITLE
anything change with form edit width property?

### ISSUE THREAD

**Issue by bchr02** [openpsa/jsgrid#103] opened 2015-02-04 18:38 UTC
I can't seem to change the width of the form edit window regardless which of the following two methods I use:
````javascript
$.extend($.jgrid.edit, {width: 1000}); 
````
or

````javscript
$("#grid").jqGrid(
	'navGrid',
	'#pager',
	{add: false, edit: true, del: false}, // navGrid options
	{width: 800}  // Edit options
);
````
Demonstration site: http://www.tesllc.aero/temp/jqgrid/

Did anything change or is this a bug? 

Thanks for your help.

**Comment by flack** [comment] 2015-02-04 19:32
Hi!

I have debugged this a little, and it it comes either from a merge conflict with Oleg's code, or we just merged a bug that he fixed in a later revision. I've tried cherry-picking some stuff, but it was impossible, the delta is too big. The problem is that the third parameter here:

https://github.com/openpsa/jsgrid/blob/master/js/grid.formedit.js#L1007

is wrong. I don't have any time to debug this today, but I'll take a look soon, unless someone else beats me to it :-)

**Comment by bchr02** [comment] 2015-02-04 19:46
Okay, thank you.

**Comment by bouks** [comment] 2015-02-04 19:52
Fixed here :

https://github.com/openpsa/jsgrid/commit/ecc9a21dbd043303c1257bed3f02a19a77f93b3e

It's my fault, i've deleted the width line by error :

https://github.com/openpsa/jsgrid/commit/e0f44aaf4a0d4e93c38eebe14ccc1874a0c8f825

**Closed by bouks** 2015-02-04 19:52 UTC

**Comment by bchr02** [comment] 2015-02-04 21:16
thanks for fixing this.

**Comment by bchr02** [comment] 2015-02-04 21:32
I just updated using bower but the changes were not there? When does bower see the new commit?

**Comment by meh-uk** [comment] 2015-02-04 21:34
Has the change been built?

**Comment by bouks** [comment] 2015-02-04 21:47
No. I never build, i let flack doing it. Can you do it Matthew ?

**Comment by meh-uk** [comment] 2015-02-04 21:52
I'm afraid not as I don't have access to my computer. I can try and do so tomorrow.

**Comment by bchr02** [comment] 2015-02-04 22:06
no worries. no rush. just curious.. Thanks guys

**Comment by flack** [comment] 2015-02-04 22:17
Ok, I've updated the build now.

@bouks There's no magic involved with the build, just run `grunt` without any parameters and then commit the `dist` folder. Maybe I'll write another grunt task to do it in one command someday :-)

BTW: This is the reason we need to keep the dist folder in the repo after all: Because otherwise, bower users will get nothing useful. But we should of course still do the prebuilt zip we've talked about in #93

**Comment by bouks** [comment] 2015-02-04 22:20
Flack Bower, less than 24h... :)

**Comment by bchr02** [comment] 2015-02-04 23:06
Not sure if this is related but something else that is not working is closeAfterEdit when placed in:
````javascript
$("#grid").jqGrid(
    'navGrid',
    '#pager',
    {add: false, edit: true, del: false}, // navGrid options
    {closeAfterEdit: true}  // Edit options
);
````

**However** it does work when placed in 
````javascript
$.extend($.jgrid.edit, {closeAfterEdit: true}); 
````

**Comment by bouks** [comment] 2015-02-05 12:08
@bchr02 It is not the same bug. It would be cool @bchr02 if you open a new issue that can be open with good title (example: "edit option closeAfterEdit not functioning"), then bug fix, history and management will be better. :)

**Comment by bchr02** [comment] 2015-02-05 14:26
Okay done. https://github.com/openpsa/jsgrid/issues/104
