### ISSUE TITLE
Base in builder

### ISSUE THREAD

**Issue by bouks** [openpsa/jsgrid#108] opened 2015-02-07 11:56 UTC
Actually it is possible to choose various components AND not choose "base" in builder.

Is it good ?

**Comment by meh-uk** [comment] 2015-02-07 11:58
I don't think so.

**Comment by flack** [comment] 2015-02-07 12:03
@bouks This used to be possible, but not anymore `grid.base.js` is uncoditionally included in the current version, there is no checkbox to deselect it. If you managed to build a zip that doesn't include base, please let me to know the steps to reproduce

**Comment by bouks** [comment] 2015-02-07 12:08
Ok. So it's just confusionning to have a checkbox with "Base". Maybe we should remove it ? Base fieldset is very short so no need to have a check/uncheck all checkbox.

**Comment by flack** [comment] 2015-02-07 12:10
The checkbox before "Base" is actually just a helper to select all elements in this group. I'll change the styling so that it can't be confused with the module selection checkboxes that easily

**Comment by flack** [comment] 2015-02-07 12:53
I've changed the laoyut now in https://github.com/openpsa/jsgrid/commit/cd58d9f22c4f6a5e9be21146b78ae0e1400e30ba, it looks like this now:

![bildschirmfoto 2015-02-07 um 13 51 43](https://cloud.githubusercontent.com/assets/425166/6092143/8397fda4-aed0-11e4-9d9b-6bf30a1c8aff.png)

Not sure if it's less confusing, but I hope for the best :-)

**Comment by meh-uk** [comment] 2015-02-07 22:54
That looks ok, so closing.

**Closed by meh-uk** 2015-02-07 22:54 UTC
Labels: builder, question
